export default [{
  id: 0, 
  name: 'President',
  surname: 'Asshole, Capitalism or Scum',
  description: 'Race to get rid of all of the cards in their hands in order to become "president"',
  imageUrl: 'images/President.png',
  minPlayers: 4,
  maxPlayers: 8,
  minTime: 5,
  maxTime: 15,
  classAttBackground: 'bg-primary me-md-3 pt-3 px-3 pt-md-3 px-md-5 text-center text-white overflow-hidden',
  classAttPlayers: 'badge bg-light text-dark',
  classAttTime: 'badge rounded-pill bg-light text-dark',
  classAttButton: 'btn btn-light',
  classAttImage: 'bg-light shadow-sm mx-auto card-block',
}, {
  id: 1, 
  name: 'Durak',
  surname: '"Fool", Kur or Russian War',
  description: 'Attack your opponents and defend yourself from others so as not to become the "fool"',
  imageUrl: 'images/Durak.png',
  minPlayers: 2,
  maxPlayers: 6,
  minTime: 5,
  maxTime: 15,
  classAttBackground: 'bg-danger me-md-3 pt-3 px-3 pt-md-3 px-md-5 text-center text-white overflow-hidden',
  classAttPlayers: 'badge bg-warning',
  classAttTime: 'badge rounded-pill bg-warning',
  classAttButton: 'btn btn-warning text-white',
  classAttImage: 'bg-warning shadow-sm mx-auto card-block'
}];