export default [{
  id: 'president01', 
  name: 'President',
  surname: 'Asshole, Capitalism or Scum',
  description: 'Race to get rid of all of your cards in order to become "president"',
  imageUrl: 'images/President.png',
  minPlayers: 4,
  maxPlayers: 8,
  minTime: 5,
  maxTime: 15,
  category: 'Party',
  classAttBackground: 'bg-primary',
  classAttPlayers: 'bg-light text-dark',
  classAttTime: 'bg-light text-dark',
  classAttButton: 'btn-light',
  classAttImage: 'bg-light',
}, {
  id: 'durak02', 
  name: 'Durak',
  surname: '"Fool", Kur or Russian War',
  description: 'Attack your opponents and defend yourself from others so as not to become the "fool"',
  imageUrl: 'images/Durak.png',
  minPlayers: 2,
  maxPlayers: 6,
  minTime: 5,
  maxTime: 15,
  category: 'Strategy',
  classAttBackground: 'bg-danger',
  classAttPlayers: 'bg-warning',
  classAttTime: 'bg-warning',
  classAttButton: 'btn-warning text-white',
  classAttImage: 'bg-warning'
}, {
  id: 'mentiroso03', 
  name: 'Mentiroso',
  surname: '"Bullshit" or "Desconfío"',
  description: 'Lie, cheat and hunt the other liars to get rid of all your cards',
  imageUrl: 'images/Mentiroso.jpg',
  minPlayers: 4,
  maxPlayers: 7,
  minTime: 10,
  maxTime: 20,
  category: 'Frenetic',
  classAttBackground: 'bg-dark',
  classAttPlayers: 'bg-warning',
  classAttTime: 'bg-warning',
  classAttButton: 'btn-warning text-white',
  classAttImage: 'bg-warning'
}];